# Generated by Django 5.0.1 on 2024-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
