# Generated by Django 5.0.1 on 2024-01-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
