# Generated by Django 5.0.1 on 2024-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_category_delete_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='gallery')),
                ('youtube_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Qaleriya',
                'verbose_name_plural': 'Qaleriya',
            },
        ),
    ]
