# Generated by Django 5.0.1 on 2024-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
